export const LOGIN_START = 'login/LOGIN_START'
export const LOGIN_SUCCESS = 'login/LOGIN_SUCCESS'
export const LOGIN_ERROR = 'login/LOGIN_ERROR'
export const LOGIN_OUT = 'login/LOGIN_OUT'
export const CLEAR_USER = 'login/CLEAR_USER'
